[package]
name = "orde-rs"
version = "0.1.0"
authors = ["john.ward <john.ward@dai.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.0"